name: 'commit to github'
description: 'Commits any changed files using GitHub API'
author: 'getsentry'
branding:
  icon: 'edit-3'
  color: 'purple'
inputs:
  github-token:
    description: 'GitHub token'
    required: true
    default: '${{ github.token }}'
runs:
  using: 'node12'
  main: 'dist/index.js'
